### ISSUE TITLE
Add ability for a Badge to hold a tag

### ISSUE THREAD

**Issue by rubengees** [luxiliu/BadgeLayout#3]
The `OnBadgeClickedListener` currently passes the `Badge` to the caller in case of a click. The badge can only hold a `text` and this introduces the problem that I don't have all the information I might want to respond correctly in case of a click.

Maybe this example makes more clear what the problem is:
```java
private void respondToBadgeClick(String genre, String genreText) {
    // Do something meaningful
}

genres.addOnBadgeClickedListener(new BadgeLayout.OnBadgeClickedListener() {
    @Override
    public void onBadgeClicked(BadgeLayout.Badge badge) {
        // respondToBadgeClick(...)
        // genre could be badge.getText(), but
        // no way to now the corresponding genreText!
    }
});
```

What I propose is something like `Badge#setTag(Object)`. This would allow for setting whatever additional data is needed. It would look like this in the example above:

```java
genres.addBadge(genres.newBadge()
        .setText("Some genre")
        .setTag("Some genreText"));

genres.addOnBadgeClickedListener(new BadgeLayout.OnBadgeClickedListener() {
    @Override
    public void onBadgeClicked(BadgeLayout.Badge badge) {
        respondToBadgeClick(badge.getText(), (String) badge.getTag());
    }
});
```

This is also consistent with how Androids `View` does it.

**Comment by luxiliu** [comment]
Fixed
